CREATE TABLE `BP250_ACD_GROUPS` (
  `ID` int(11) NOT NULL auto_increment,
  `GROUP_EXT` char(8)  NOT NULL,
  `GROUP_NAME_SHORT` char(5)  NOT NULL,
  `GROUP_NAME_FULL` char(30)  NOT NULL,
  `LAST_EDIT` datetime,
  `INSERT_DATE` datetime,
  PRIMARY KEY  (`ID`),
  KEY `GROUP_EXT_IDX` (`GROUP_EXT`)
) ENGINE=InnoDB;

CREATE TRIGGER BP250_GI BEFORE INSERT ON `BP250_ACD_GROUPS`
    FOR EACH ROW SET NEW.LAST_EDIT = IFNULL(NEW.LAST_EDIT, NOW()), NEW.INSERT_DATE = IFNULL(NEW.INSERT_DATE, NOW());
-- split line

CREATE TRIGGER BP250_GU BEFORE UPDATE ON `BP250_ACD_GROUPS`
    FOR EACH ROW SET NEW.LAST_EDIT = NOW();
-- split line

CREATE TABLE `BP250_ACD_OPERATORS` (
  `ID` int(11) NOT NULL auto_increment,
  `GROUP_EXT` char(8)  NOT NULL,
  `EXT` char(8)  NOT NULL,
  `OPERATOR_NUMBER` char(8)  NOT NULL,
  `OPERATOR_NAME` char(30)  NOT NULL,
  `LAST_EDIT` datetime,
  `INSERT_DATE` datetime,
  PRIMARY KEY  (`ID`),
  KEY `OPERATORS_EXT_IDX` (`EXT`)
  KEY `GROUP_EXT_INX` (`GROUP_EXT`)
) ENGINE=InnoDB;

CREATE TRIGGER BP250_OI BEFORE INSERT ON `BP250_ACD_OPERATORS`
    FOR EACH ROW SET NEW.LAST_EDIT = IFNULL(NEW.LAST_EDIT, NOW()), NEW.INSERT_DATE = IFNULL(NEW.INSERT_DATE, NOW());
-- split line

CREATE TRIGGER BP250_OU BEFORE UPDATE ON `BP250_ACD_OPERATORS`
    FOR EACH ROW SET NEW.LAST_EDIT = NOW();
-- split line