CREATE TABLE `calls` (
  `ID` int(11) NOT NULL auto_increment,
  `CALL_TIME_START_UTC` datetime  NOT NULL,
  `CALL_DATE_START` date  NOT NULL,
  `CALL_TIME_START` time  NOT NULL,
  `CALL_DATE_END` date  NOT NULL,
  `CALL_TIME_END` time  NOT NULL,
  `TAG` int(5)  NOT NULL,
  `TRUNK` char(4)  NOT NULL,
  `EXT` char(8)  NOT NULL,
  `DURATION` time NOT NULL,
  `DURATION_S` int(5)  NOT NULL,
  `RING` time  NOT NULL,
  `A_NUMBER` char(20)  NOT NULL,
  `ACC` char(5) NOT NULL,
  `DIALLED_NUMBER` char(24)  NOT NULL,
  `SENT_NUMBER` char(24)  NOT NULL,
  `ORG_TERM` char(2)  NOT NULL,
  `TRANSFER_CONDITION` char(2)  NOT NULL,
  `CALL_TYPE` char(1)  NOT NULL,
  `CALL_VIA_FAC` char(1)  NOT NULL,
  `PBX_IDENTIFIER` char(128)  NOT NULL,
  `LAST_EDIT` datetime,
  `INSERT_DATE` datetime,
  PRIMARY KEY  (`ID`),
  KEY `CALL_TIME_START_UTC_IDX` (`CALL_TIME_START_UTC`),
  KEY `CALL_DATE_START_IDX` (`CALL_DATE_START`),
  KEY `CALL_TIME_START_IDX` (`CALL_TIME_START`),
  KEY `EXT_IDX` (`EXT`),
  KEY `DIALLED_IDX` (`DIALLED_NUMBER`)
) ENGINE=InnoDB;

CREATE TRIGGER CALLS_BP250_BI BEFORE INSERT ON `calls`
    FOR EACH ROW SET NEW.LAST_EDIT = IFNULL(NEW.LAST_EDIT, NOW()), NEW.INSERT_DATE = IFNULL(NEW.INSERT_DATE, NOW());
-- split line

CREATE TRIGGER CALLS_BP250_BU BEFORE UPDATE ON `calls`
    FOR EACH ROW SET NEW.LAST_EDIT = NOW();
-- split line